name: Run unit tests 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3  # Aktualizace na v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Aktualizace na v3
        with:
          node-version: '20'  # Použij verzi, kterou potřebuješ

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
